# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: book.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nbook.proto\"c\n\x04\x42ook\x12\x0c\n\x04ISBN\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\t\x12\x15\n\x05genre\x18\x04 \x01(\x0e\x32\x06.Genre\x12\x17\n\x0fpublishing_year\x18\x05 \x01(\x05\".\n\x11\x43reateBookRequest\x12\x19\n\nbookDetail\x18\x01 \x01(\x0b\x32\x05.Book\")\n\x12\x43reateBookResponse\x12\x13\n\x0bresponseMsg\x18\x01 \x01(\t\"\x1e\n\x0eGetBookRequest\x12\x0c\n\x04ISBN\x18\x01 \x01(\t\",\n\x0fGetBookResponse\x12\x19\n\nbookDetail\x18\x01 \x01(\x0b\x32\x05.Book\"a\n\rInventoryItem\x12\x18\n\x10inventory_number\x18\x01 \x01(\x05\x12\x15\n\x04item\x18\x02 \x01(\x0b\x32\x05.BookH\x00\x12\x17\n\x06status\x18\x03 \x01(\x0e\x32\x07.StatusB\x06\n\x04\x62ook*]\n\x05Genre\x12\n\n\x06\x41\x43TION\x10\x00\x12\n\n\x06\x43OMEDY\x10\x01\x12\t\n\x05\x44RAMA\x10\x02\x12\x0b\n\x07\x46\x41NTASY\x10\x03\x12\n\n\x06HORROR\x10\x04\x12\x0b\n\x07MYSTERY\x10\x05\x12\x0b\n\x07ROMANCE\x10\x06*\"\n\x06Status\x12\r\n\tAVAILABLE\x10\x00\x12\t\n\x05TAKEN\x10\x01\x32w\n\x10InventoryService\x12,\n\x07GetBook\x12\x0f.GetBookRequest\x1a\x10.GetBookResponse\x12\x35\n\nCreateBook\x12\x12.CreateBookRequest\x1a\x13.CreateBookResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'book_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GENRE._serialized_start=383
  _GENRE._serialized_end=476
  _STATUS._serialized_start=478
  _STATUS._serialized_end=512
  _BOOK._serialized_start=14
  _BOOK._serialized_end=113
  _CREATEBOOKREQUEST._serialized_start=115
  _CREATEBOOKREQUEST._serialized_end=161
  _CREATEBOOKRESPONSE._serialized_start=163
  _CREATEBOOKRESPONSE._serialized_end=204
  _GETBOOKREQUEST._serialized_start=206
  _GETBOOKREQUEST._serialized_end=236
  _GETBOOKRESPONSE._serialized_start=238
  _GETBOOKRESPONSE._serialized_end=282
  _INVENTORYITEM._serialized_start=284
  _INVENTORYITEM._serialized_end=381
  _INVENTORYSERVICE._serialized_start=514
  _INVENTORYSERVICE._serialized_end=633
# @@protoc_insertion_point(module_scope)
